"use client";

export default function ReportPage() {
  return (
    <div className="animate-fade-in" style={{ maxWidth: '900px', margin: '0 auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '2rem' }}>
        <h2>SkillGap Executive Report</h2>
        <button 
          className="btn btn-primary"
          onClick={() => window.print()}
        >
          Export as PDF
        </button>
      </div>

      <div className="card" style={{ padding: '3rem', backgroundColor: '#fff', color: '#000' }}>
        <h1 style={{ color: '#000', borderBottom: '2px solid #eee', paddingBottom: '1rem', marginBottom: '2rem' }}>
          SkillTwin Readiness Report
        </h1>
        
        <div style={{ marginBottom: '2rem' }}>
          <h3 style={{ color: '#333' }}>Profile Summary</h3>
          <p><strong>Candidate:</strong> torvalds (GitHub)</p>
          <p><strong>Target Role:</strong> Frontend Developer at Google</p>
          <p><strong>Overall Readiness Score:</strong> <span style={{ color: '#d97706', fontWeight: 'bold' }}>65%</span></p>
        </div>

        <div style={{ marginBottom: '2rem' }}>
          <h3 style={{ color: '#333' }}>Critical Skill Gaps (Blockers)</h3>
          <ul style={{ paddingLeft: '1.5rem', lineHeight: 1.8 }}>
            <li><strong>Next.js:</strong> Current Level 0 ➔ Required Level 3</li>
          </ul>
        </div>

        <div style={{ marginBottom: '2rem' }}>
          <h3 style={{ color: '#333' }}>Recommended Learning Roadmap</h3>
          <ul style={{ paddingLeft: '1.5rem', lineHeight: 1.8 }}>
            <li><strong>Week 1:</strong> Next.js Fundamentals (10 hours)</li>
            <li><strong>Week 2:</strong> Advanced Next.js (12 hours)</li>
            <li><strong>Week 3:</strong> System Design Basics (8 hours)</li>
          </ul>
        </div>

        <div style={{ borderTop: '1px solid #eee', paddingTop: '2rem', textAlign: 'center', fontSize: '0.875rem', color: '#666' }}>
          Generated by SkillTwin AI Engine • {new Date().toLocaleDateString()}
        </div>
      </div>
    </div>
  );
}
